version: '3.8'

services:
  mininova.api:
    image: mininova.api
    build:
      context: .
      dockerfile: src/MiniNova.API/Dockerfile
    ports:
      - "5167:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MNPConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ValidInMinutes=${JWT_VALID_MINUTES}
    volumes:
      - ./src/MiniNova.API/Keys:/app/Keys
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: mininova_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  client:
    build:
      context: ./src/Client 
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src/Client:/app
      - /app/node_modules    
    environment:
      - VITE_API_URL=http://localhost:5167
    depends_on:
      - mininova.api

volumes:
  pgdata: